import {
  Appointment,
  AppointmentStatus,
  AppointmentType,
} from '../models/appointment.model';

export const DUMMY_APPOINTMENTS: Appointment[] = [
  {
    id: 1,
    title: 'اختبار القدرة المعرفية-التخصصات العلمية',
    date: '2024-08-11T00:00:00.000Z',
    startTime: '9:00',
    endTime: '11:00',
    location: 'جامعة أم القرى-العابدية',
    status: AppointmentStatus.Scheduled,
    appointmentType: AppointmentType.CheckUp,
    details: `This has script <script> console.log("XXH attack!!) </script>`,
    clientName: 'أحمد محمد',
    clientPhone: '0501234567',
    clientEmail: 'ahmed@example.com',
  },
  {
    id: 2,
    title: 'استشارة طبية عامة',
    date: '2024-08-12T00:00:00.000Z',
    startTime: '14:00',
    endTime: '15:00',
    location: 'مستشفى الملك عبدالعزيز',
    status: AppointmentStatus.Scheduled,
    appointmentType: AppointmentType.Consultation,
    details: 'اختبار القدرة المعرفية-التخصصات العلمية',
    clientName: 'أحمد محمد',
    clientPhone: '0501234567',
    clientEmail: 'ahmed@example.com',
  },
  {
    id: 3,
    title: 'متابعة حالة المريض',
    date: '2024-08-10T00:00:00.000Z',
    startTime: '10:30',
    endTime: '11:30',
    location: 'عيادة الدكتور خالد',
    status: AppointmentStatus.Completed,
    appointmentType: AppointmentType.FollowUp,
    details: 'اختبار القدرة المعرفية-التخصصات العلمية',
    clientName: 'سارة عبدالله',
    clientPhone: '0559876543',
    clientEmail: 'sara@example.com',
  },
  {
    id: 4,
    title: 'حالة طارئة',
    date: '2024-08-13T00:00:00.000Z',
    startTime: '16:00',
    endTime: '17:00',
    location: 'مستشفى الملك فهد',
    status: AppointmentStatus.Scheduled,
    appointmentType: AppointmentType.Emergency,
    details: 'اختبار القدرة المعرفية-التخصصات العلمية',
    clientName: 'محمد علي',
    clientPhone: '0567891234',
    clientEmail: 'mohammed@example.com',
  },
  {
    id: 5,
    title: 'فحص دوري',
    date: '2024-08-09T00:00:00.000Z',
    startTime: '11:00',
    endTime: '12:00',
    location: 'مركز صحي الروضة',
    status: AppointmentStatus.Cancelled,
    appointmentType: AppointmentType.CheckUp,
    details: 'اختبار القدرة المعرفية-التخصصات العلمية',
    clientName: 'فاطمة أحمد',
    clientPhone: '0512345678',
    clientEmail: 'fatima@example.com',
  },
  {
    id: 6,
    title: 'استشارة نفسية',
    date: '2024-08-14T00:00:00.000Z',
    startTime: '13:00',
    endTime: '14:00',
    location: 'مركز الصحة النفسية',
    status: AppointmentStatus.Scheduled,
    appointmentType: AppointmentType.Consultation,
    details: '<ul><li><b><h1>html</h1></b></li></ul>',
    clientName: 'عبدالرحمن سعيد',
    clientPhone: '0598765432',
    clientEmail: 'abdulrahman@example.com',
  },
  {
    id: 7,
    title: 'متابعة بعد العملية',
    date: '2024-08-08T00:00:00.000Z',
    startTime: '15:30',
    endTime: '16:30',
    location: 'مستشفى الملك خالد',
    status: AppointmentStatus.Completed,
    appointmentType: AppointmentType.FollowUp,
    details: 'اختبار القدرة المعرفية-التخصصات العلمية',
    clientName: 'نورة محمد',
    clientPhone: '0576543210',
    clientEmail: 'noura@example.com',
  },
];
